In [2]:
#Appendix 1 libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
#appendix 2 libraries
from sklearn.preprocessing import MinMaxScaler, RobustScaler, LabelEncoder
from sklearn.impute import SimpleImputer, KNNImputer
# machine learning task
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
# import pipeline
from sklearn.pipeline import Pipeline
# For classification task
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
#appendix 3 libraries
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
# Load the Dataset
dataset= pd.read_csv('/content/collegePlace.csv')
print(dataset)
# Data Exploration,Preprocessing and basics concepts
print(dataset.head())
print(dataset.shape)
print(dataset.columns.dtype)
print(dataset.duplicated().sum())
print(dataset.isnull().sum())
print(dataset.info)
print(dataset.describe())
print(dataset.nunique())
print(dataset['Age'].unique())
print(dataset['Age'].value_counts())
print(dataset['Gender'].unique())
print(dataset['Gender'].value_counts())
print(dataset['PlacedOrNot'].unique())
print(dataset['PlacedOrNot'].value_counts())
print(dataset.Stream.value_counts())
print(dataset['Internships'].value_counts())

      Age  Gender                         Stream  Internships  CGPA  Hostel  \
0      22    Male  Electronics And Communication            1     8       1
1      21  Female               Computer Science            0     7       1
2      22  Female         Information Technology            1     6       0
3      21    Male         Information Technology            0     8       0
4      22    Male                     Mechanical            0     8       1
...   ...     ...                            ...          ...   ...     ...
2961   23    Male         Information Technology            0     7       0
2962   23    Male                     Mechanical            1     7       1
2963   22    Male         Information Technology            1     7       0
2964   22    Male               Computer Science            1     7       0
2965   23    Male                          Civil            0     8       0

      HistoryOfBacklogs  PlacedOrNot
0                     1            1
1                     1            1
2                     0            1
3                     1            1
4                     0            1
...                 ...          ...
2961                  0            0
2962                  0            0
2963                  0            0
2964                  0            0
2965                  0            1

[2966 rows x 8 columns]
   Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1
1   21  Female               Computer Science            0     7       1
2   22  Female         Information Technology            1     6       0
3   21    Male         Information Technology            0     8       0
4   22    Male                     Mechanical            0     8       1

   HistoryOfBacklogs  PlacedOrNot
0                  1            1
1                  1            1
2                  0            1
3                  1            1
4                  0            1
(2966, 8)
object
1829
Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64
<bound method DataFrame.info of       Age  Gender                         Stream  Internships  CGPA  Hostel  \
0      22    Male  Electronics And Communication            1     8       1
1      21  Female               Computer Science            0     7       1
2      22  Female         Information Technology            1     6       0
3      21    Male         Information Technology            0     8       0
4      22    Male                     Mechanical            0     8       1
...   ...     ...                            ...          ...   ...     ...
2961   23    Male         Information Technology            0     7       0
2962   23    Male                     Mechanical            1     7       1
2963   22    Male         Information Technology            1     7       0
2964   22    Male               Computer Science            1     7       0
2965   23    Male                          Civil            0     8       0

      HistoryOfBacklogs  PlacedOrNot
0                     1            1
1                     1            1
2                     0            1
3                     1            1
4                     0            1
...                 ...          ...
2961                  0            0
2962                  0            0
2963                  0            0
2964                  0            0
2965                  0            1

[2966 rows x 8 columns]>
               Age  Internships         CGPA       Hostel  HistoryOfBacklogs  \
count  2966.000000  2966.000000  2966.000000  2966.000000        2966.000000
mean     21.485840     0.703641     7.073837     0.269049           0.192178
std       1.324933     0.740197     0.967748     0.443540           0.394079
min      19.000000     0.000000     5.000000     0.000000           0.000000
25%      21.000000     0.000000     6.000000     0.000000           0.000000
50%      21.000000     1.000000     7.000000     0.000000           0.000000
75%      22.000000     1.000000     8.000000     1.000000           0.000000
max      30.000000     3.000000     9.000000     1.000000           1.000000

       PlacedOrNot
count  2966.000000
mean      0.552596
std       0.497310
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000
Age                  11
Gender                2
Stream                6
Internships           4
CGPA                  5
Hostel                2
HistoryOfBacklogs     2
PlacedOrNot           2
dtype: int64
[22 21 23 24 28 30 25 26 20 19 29]
Age
21    1084
22     941
20     375
23     195
19     156
24     131
26      50
25      29
28       3
30       1
29       1
Name: count, dtype: int64
['Male' 'Female']
Gender
Male      2475
Female     491
Name: count, dtype: int64
[1 0]
PlacedOrNot
1    1639
0    1327
Name: count, dtype: int64
Stream
Computer Science                 776
Information Technology           691
Electronics And Communication    424
Mechanical                       424
Electrical                       334
Civil                            317
Name: count, dtype: int64
Internships
0    1331
1    1234
2     350
3      51
Name: count, dtype: int64

#Output



```
   Age  Gender                         Stream  Internships  CGPA  Hostel  \
0      22    Male  Electronics And Communication            1     8       1   
1      21  Female               Computer Science            0     7       1   
2      22  Female         Information Technology            1     6       0   
3      21    Male         Information Technology            0     8       0   
4      22    Male                     Mechanical            0     8       1   
...   ...     ...                            ...          ...   ...     ...   
2961   23    Male         Information Technology            0     7       0   
2962   23    Male                     Mechanical            1     7       1   
2963   22    Male         Information Technology            1     7       0   
2964   22    Male               Computer Science            1     7       0   
2965   23    Male                          Civil            0     8       0   

      HistoryOfBacklogs  PlacedOrNot  
0                     1            1  
1                     1            1  
2                     0            1  
3                     1            1  
4                     0            1  
...                 ...          ...  
2961                  0            0  
2962                  0            0  
2963                  0            0  
2964                  0            0  
2965                  0            1  

[2966 rows x 8 columns]
   Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1  
(2966, 8)
object
1829
Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64
<bound method DataFrame.info of       Age  Gender                         Stream  Internships  CGPA  Hostel  \
0      22    Male  Electronics And Communication            1     8       1   
1      21  Female               Computer Science            0     7       1   
2      22  Female         Information Technology            1     6       0   
3      21    Male         Information Technology            0     8       0   
4      22    Male                     Mechanical            0     8       1   
...   ...     ...                            ...          ...   ...     ...   
2961   23    Male         Information Technology            0     7       0   
2962   23    Male                     Mechanical            1     7       1   
2963   22    Male         Information Technology            1     7       0   
2964   22    Male               Computer Science            1     7       0   
2965   23    Male                          Civil            0     8       0   

      HistoryOfBacklogs  PlacedOrNot  
0                     1            1  
1                     1            1  
2                     0            1  
3                     1            1  
4                     0            1  
...                 ...          ...  
2961                  0            0  
2962                  0            0  
2963                  0            0  
2964                  0            0  
2965                  0            1  

[2966 rows x 8 columns]>
               Age  Internships         CGPA       Hostel  HistoryOfBacklogs  \
count  2966.000000  2966.000000  2966.000000  2966.000000        2966.000000   
mean     21.485840     0.703641     7.073837     0.269049           0.192178   
std       1.324933     0.740197     0.967748     0.443540           0.394079   
min      19.000000     0.000000     5.000000     0.000000           0.000000   
25%      21.000000     0.000000     6.000000     0.000000           0.000000   
50%      21.000000     1.000000     7.000000     0.000000           0.000000   
75%      22.000000     1.000000     8.000000     1.000000           0.000000   
max      30.000000     3.000000     9.000000     1.000000           1.000000   

       PlacedOrNot  
count  2966.000000  
mean      0.552596  
std       0.497310  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000  
Age                  11
Gender                2
Stream                6
Internships           4
CGPA                  5
Hostel                2
HistoryOfBacklogs     2
PlacedOrNot           2
dtype: int64
[22 21 23 24 28 30 25 26 20 19 29]
Age
21    1084
22     941
20     375
23     195
19     156
24     131
26      50
25      29
28       3
30       1
29       1
Name: count, dtype: int64
['Male' 'Female']
Gender
Male      2475
Female     491
Name: count, dtype: int64
[1 0]
PlacedOrNot
1    1639
0    1327
Name: count, dtype: int64
Stream
Computer Science                 776
Information Technology           691
Electronics And Communication    424
Mechanical                       424
Electrical                       334
Civil                            317
Name: count, dtype: int64
Internships
0    1331
1    1234
2     350
3      51
Name: count, dtype: int64
```